apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quotes-go
  description: Quotes service written in Go
  labels:
    earthly.dev/demo: true
  annotations:
    earthly.dev/service-discovery: quotesgo
  links:
    - url: https://foo.bar
      title: Grafana Link
spec:
  type: website5
  lifecycle: production
  owner: eng-team
  system: public-websites