apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quotes-go
  description: Quotes service written in Go
  labels:
    earthly.dev/demo: true
  annotations:
    earthly.dev/service-discovery: quotesgo
  tags:
    - golang
  links:
    - url: https://foo.bar
spec:
  type: website
  lifecycle: production
  owner: eng-team
  system: public-websites
