name: lunar-e2e-after-ci-pipeline-5a248c2f3
on:
  push:
    paths: [".github/workflows/lunar-e2e-after-ci-pipeline-5a248c2f3.yml"]
permissions:
  contents: read
jobs:
  build:
    runs-on: localdev-e2e-test-37636305882-1-github-3-e2e
    steps:
      - run: '[ "${{ github.run_attempt }}" != 1 ] || { echo "attempt 1 fails so it can be re-run"; exit 1; }'
