name: lunar-e2e-pin-rotation-69dd61363
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 69dd61363'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-69dd61363'
    runs-on: localdev-e2e-test-37161955145-1-github-3-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 69dd61363'
