name: lunar-e2e-pin-rotation-a236addf1
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened a236addf1'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-a236addf1'
    runs-on: localdev-e2e-test-36385130484-1-github-1-e2e
    steps:
      - run: /bin/echo 'pin rotation CI a236addf1'
