name: lunar-e2e-exwu3wsg
on: push
jobs:
  e2e:
    runs-on: localdev-nacho-e2e
    steps:
      - name: Step number 1
        run: |
          printf 'step 1 start\n'
          printf 'step 1 complete\n'
      - name: Step number 2
        run: |
          printf 'step 2 start\n'
          printf 'step 2 middle\n'
          printf 'step 2 complete\n'
      - name: Step number 3
        run: |
          printf 'step 3 start\n'
          printf 'step 3 middle\n'
          printf 'step 3 complete\n'
      - name: Step number 4
        run: |
          printf 'step 4 start\n'
          printf 'step 4 complete\n'
