name: lunar-e2e-pin-rotation-81313f921
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 81313f921'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-81313f921'
    runs-on: localdev-e2e-test-36333340880-3-github-1-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 81313f921'
