name: lunar-e2e-pin-rotation-c6fcf9621
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened c6fcf9621'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-c6fcf9621'
    runs-on: localdev-e2e-test-36863457946-1-github-1-e2e
    steps:
      - run: /bin/echo 'pin rotation CI c6fcf9621'
