name: lunar-e2e-telemetry-aa8f291e1
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-aa8f291e1.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-aa8f291e1
    runs-on: localdev-e2e-test-37128745105-1-github-1-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=aa8f291e1)"
