name: lunar-e2e-buftest-hosted
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-buftest-hosted.yml
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      LUNAR_HUB_HOST: e920-85-152-125-62.ngrok-free.app
      LUNAR_HUB_GRPC_PORT: "443"
      LUNAR_HUB_HTTP_PORT: "443"
      LUNAR_HUB_INSECURE: "false"
      LUNAR_HUB_TOKEN: token
      LUNAR_STRICT_MODE: "true"
      GODEBUG: "http2debug=2"
    steps:
      - uses: earthly/lunar-ci-tracer@v2.4.0
      - name: Step number 1
        run: |
          /bin/echo 'step 1 start'
          /bin/echo 'step 1 complete'
      - name: Step number 2
        run: |
          /bin/echo 'step 2 start'
          /bin/echo 'step 2 middle'
          /bin/echo 'step 2 complete'
      - name: Step number 3
        run: |
          /bin/echo 'step 3 start'
          /bin/echo 'step 3 middle'
          /bin/echo 'step 3 complete'
      - name: Step number 4
        run: |
          /bin/echo 'step 4 start'
          /bin/echo 'step 4 complete'

