name: lunar-e2e-workflow-end-thf6m70l
on:
  push:
    paths: [".github/workflows/lunar-e2e-workflow-end-thf6m70l.yml"]
permissions:
  contents: read
jobs:
  build:
    runs-on: localdev-bender-e2e
    steps:
      - run: '[ "${{ github.run_attempt }}" != 1 ] || { echo "attempt 1 fails so it can be re-run"; exit 1; }'
