name: lunar-e2e-telemetry-67df06872
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-67df06872.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-67df06872
    runs-on: localdev-e2e-test-37470308554-1-github-2-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=67df06872)"
