name: lunar-e2e-telemetry-54e86cc11
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-54e86cc11.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-54e86cc11
    runs-on: localdev-e2e-test-37197458464-1-github-1-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=54e86cc11)"
