name: lunar-e2e-telemetry-788adb062
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-788adb062.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-788adb062
    runs-on: localdev-e2e-test-37486135960-1-github-2-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=788adb062)"
