name: lunar-e2e-telemetry-403a87442
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-403a87442.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-403a87442
    runs-on: localdev-e2e-test-37331688919-1-github-2-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=403a87442)"
