name: lunar-e2e-pin-rotation-ee60a4e81
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened ee60a4e81'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-ee60a4e81'
    runs-on: localdev-e2e-test-36530703684-1-github-1-e2e
    steps:
      - run: /bin/echo 'pin rotation CI ee60a4e81'
