name: lunar-e2e-telemetry-112c30561
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-112c30561.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-112c30561
    runs-on: localdev-e2e-test-37217111529-1-github-1-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=112c30561)"
