name: lunar-e2e-telemetry-61ea93d12
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-61ea93d12.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-61ea93d12
    runs-on: localdev-e2e-test-37671162580-1-github-2-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=61ea93d12)"
