name: lunar-e2e-telemetry-4899ff5f2
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-4899ff5f2.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-4899ff5f2
    runs-on: localdev-e2e-test-37119039709-1-github-2-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=4899ff5f2)"
