name: lunar-e2e-telemetry-b131bfb71
on:
  push:
    paths:
      - .github/workflows/lunar-e2e-telemetry-b131bfb71.yml
jobs:
  telemetry-probe:
    name: telemetry-probe-b131bfb71
    runs-on: localdev-e2e-test-37136751859-1-github-1-e2e
    steps:
      - name: traced step
        run: /bin/echo "telemetry probe (TEST_ID=b131bfb71)"
