FROM cgr.dev/chainguard/go:latest-dev

LABEL application_name="backend"
LABEL description="Backend service for pantalasa quotes application"
LABEL owner="earthly"
LABEL source_uri="https://github.com/earthly/pantalasa"

RUN echo "Hello, world!"
